### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mattyjones** [mattyjones/keepassxc-packaging#1]
- [ ] add docs for how to build
- [ ] update readme with link to bug and more up-to-date info about the project
- [ ] roadmap to get a package into Debian unstable w/ checklist
- [ ] vagrant up via the `site.yml` 
- [ ] move package version to a var
- [ ] flesh out best practices
